### ISSUE TITLE
Minor API changes

### ISSUE THREAD

**Issue by franknoe** [readdy/readdy#12]
These are notes from yesterday's talk that mainly affect the C++ API:
- Rename Programs to make sure that the Simulation community understands them.
  - DiffuseProgram is the Euler Brownian Dynamics Integrator (e.g. EulerBDIntegrator).
  - UpdateModelProgram updates the Neighborlist and updates the Forces on the particles. These might actually be two different Programs with clearer naming and individually better defined functionalities and 
  - I'm not sure if having  `Program` in the name helps to find/identify program classes. If not, I'd just leave that away to make names shorter.
- Method names: Some method names are annoyingly long
- `Program` classes and  `execute` method. This is a very pedantic comment, but my feeling is that a Program and execute refers to something larger than an algorithm that you attach to a data structure do compute a step. Ideas for better names?

**Comment by clonker** [comment]
Concerning the last point, I could think of
* `action.configure(...); action.perform();`
* overloading the bracket operator, and calling it, e.g., a `step.configure(...); step();`
What is your opinion on these?

I agree that `Program` (or something else that we change it to) does not need to appear in the program classes. After all they can be found via the directory structure and they have their own namespace as well.

**Comment by chrisfroe** [comment]
We've settled on Actions that perform()
