### ISSUE TITLE
Binding Reaction

### ISSUE THREAD

**Issue by nagarrone** [readdy/readdy#121]
Hi there,

I am setting up my system, which consists of a linear homopolymer, composed by particles with a diffusion constant equal to zero, that results in a rigid and static polymer (built as a topology). We are trying to set up a binding reaction between a free diffusing particle and the polymer. We successfully established the forward binding reaction, as a spatial reaction with its own rate constant between the diffusing particles and the static topology. Our problem comes up when trying to set up the dissociation reaction, in this case, a structural reaction. I would appreciate if you could please let me know which is the best way to setup a dissociation reaction? We see that particles attach to the polymer but do not unbind. Is there a simple way of setting a binding/unbinding reaction between particles and topologies?

Thanks beforehand,

Nico

**Comment by clonker** [comment]
Hi Nico,

you can have a look at the `unstable_reaction_function` of the first topology reaction example on the documentation site: https://readdy.github.io/demonstration/topologies .

Perhaps in some more detail:
```python
def unstable_rate_function(topology):
    # this is the rate function (probability per unit time), can be made dependent on the 
    # number of particles in the topology (len(topology.particles))
    return .1
def unstable_reaction_function(topology):
    # this is the reaction function, randomly selecting a particle in the topology and separating it
    recipe = readdy.StructuralReactionRecipe(topology)
    # the random selection
    index = np.random.randint(0, len(topology.particles))
    # remove all edges in the graph that contain this vertex
    recipe.separate_vertex(index)
    # particle type can then be changed to something that is not a topology species
    recipe.change_particle_type(index, "Decay")
    return recipe
system.topologies.add_structural_reaction(topology_type="unstable",
                                          reaction_function=unstable_reaction_function, 
                                          rate_function=unstable_rate_function)
```

For your example this might look like this (bound A particle gets type TA, other topology particles have type T):
```python
def rate_function(topology):
    types = [topology.particle_type_of_vertex(v) for v in topology.get_graph().get_vertices()]
    return 1. if "TA" in types else 0.
def reaction_function(topology):
    recipe = readdy.StructuralReactionRecipe(topology)
    vertex_to_separate = None
    for index, vertex in enumerate(topology.get_graph().get_vertices()):
        if "TA" == topology.particle_type_of_vertex(vertex):
            vertex_to_separate = index
    assert vertex_to_separate is not None
    
    # separate particle
    recipe.separate_vertex(vertex_to_separate)
    recipe.change_particle_type(vertex_to_separate, "A")
    return recipe
system.topologies.add_structural_reaction("Topology", reaction_function, rate_function)
```
With the rate function you can ensure that the reaction is only evaluated if there is a "TA" particle in the topology instance.

Additionally to `particle_type_of_vertex` you can also use `position_of_vertex`, and `particle_id_of_vertex` to query further information of the current state.

We are likely going to add convenience functions in the future to ease this process, but as of now unbinding can be handled like that.

All the best,
Moritz

**Comment by nagarrone** [comment]
Hi Moritz, thank you very much for your answer,

I would like to ask you a new question about the same system. We are trying to set up the same forward binding reaction, as I previously described, but between a single particle topology and the static topology, instead of a free diffusing particle. There is no error triggered by our attempt to do this but we do not see any actual reaction on the VMD simulation. What could be the reasons for this reaction not taking place? 

Best,

Nico.

**Comment by clonker** [comment]
Hi Nico,

a guess would be the reaction rate and/or radius in combination with the time step you are using. I have uploaded you a notebook with a small working toy example: [Association and dissociation](https://github.com/readdy/readdy/files/2016969/Association.and.dissociation.zip).
There you can see how the particle attaches and detaches. It also contains a small section using the "readdyviewer" (at the very end) as an alternative to VMD. It can display the bonds and also shows how to use the currently undocumented topologies observable (going to upload some docs asap) with which you can see which topologies were present in a certain time step and which bonds and particles were involved.
If you want to try out this alternative viewer, you can also install it through conda ([here](https://github.com/readdy/readdyviewer)); however a rather new nvidia graphics card is required to use it.
Another possibility might be the ReaDDy version you are using. We recently (in the last couple weeks) made an update which fixed some issues with the topology reaction handling. The most recent version is v1.0.1. Try `conda update --force -c readdy readdy`.

Did this resolve your problem? If not it might be helpful to see the relevant part of your simulation setup.

Best,
Moritz

**Comment by clonker** [comment]
Due to the description in issue #132 i assume that you resolved this issue, closing for now. Otherwise please feel free to reopen.
