### ISSUE TITLE
Reaction Counts Observable

### ISSUE THREAD

**Issue by nagarrone** [readdy/readdy#132]
Hello there,

I am using Readdy to set up my system in which I configured one spatial reaction (binding reaction) and a structural one (unbinding reaction).  I would like to use the "Reaction" or the "Reaction Counts" observable to evaluate how many of these reactions take place per time step. When I try to use these observables in my program, there is no information stored inside the "counts" dictionary observable, which is strange because I can clearly see the reaction taking place on the VMD movie. 
How can I properly use these observables? Is there any special place in which these observables need to be recorded and/or be called back within my program?

Thank you beforehand,

Nicolas Garrone

**Comment by chrisfroe** [comment]
Hi Nicolas,

the reaction observables currently only observe "normal" reactions, i.e. exluding topology reactions. I will regard this as a (very sensible) feature request.

As a quick workaround, if your system contains __only one__ topology instance, you could record the topology observable and find out if the length of that specific topology has changed in a given timestep. I made such an example, see [this gist](https://gist.github.com/chrisfroe/8821dfe3e9f0260d7fa268d523ab4249). Cell [15] shows the polymer length as a function of time and cell [18] its one-step derivative, i.e. the change from one step to the next.

**Comment by nagarrone** [comment]
Thank you very much for your answer

Best,
Nico

**Comment by clonker** [comment]
Structural reactions should get labels upon registration then to tell them apart. Also we need to think about how to integrate this into the reaction record. Or perhaps a new obs altogether?

**Comment by clonker** [comment]
This is now available in the latest dev version.
