### ISSUE TITLE
Encountering strange behavior with Topology-Topology spatial reaction

### ISSUE THREAD

**Issue by EricJIsaac** [readdy/readdy#135]
Hello,

Currently, when using the C++ API to create and add Spatial Reactions, when I define a reaction between two topologies of a different type, the resulting topology has the type "-1". I'm not sure if this is a bug or misuse on my end.

The reaction I am trying to construct is:

"Growth: filament(end) + free(monomer) -> filament(core--end)"

and I am using the addSpatialReaction("...") function to parse this string.
For the time being, I am using a stopgap to catch invalid topologies, but I would prefer to know if this is a bug or misuse, and ultimately to resolve the issue if you can provide me any insight. 

Thanks,
-Eric

**Comment by clonker** [comment]
Oh yeah this is a bug, sorry for that! Fixing it now.
