### ISSUE TITLE
Function to reset simulation particles, Option to not initialize every-time run is called.

### ISSUE THREAD

**Issue by EricJIsaac** [readdy/readdy#136]
Hello,

I am requesting a function to clear all existing particles and topologies from the C++ api, preferably by being able to call resetParticles() or something of the sort on the simulation (or the appropriate entity).

I am also requesting a way to disable/enable initialization of the Kernel when a simulation is run (or a way to manually run it separately when needed and not have it run automatically). I am using ReaDDy to construct interactive simulations, and in many cases, I would like to be able to run a time-step without discarding or re-initializing the state that exists from the previously run simulation.

Thanks,
-Eric

**Comment by clonker** [comment]
Concerning your second point:
You can get a simulation loop object from the simulation `simulation.createLoop(dt)` which can perform the steps of the simulation loop:
```cpp
loop.runInitialize(); // kernel initialization
loop.runInitializeNeighborList(); // initialize neighbor list if needed
loop.runForces(); // calculate forces
loop.runEvaluateObservables(0); // evaluate observables
for(auto t = 1U; t <= 100; ++t) {
    loop.runIntegrator(); // propagate particles
    loop.runUpdateNeighborList(); // neighbor list update
    loop.runReactions(); // evaluate reactions
    loop.runTopologyReactions(); // and topology reactions
    loop.runUpdateNeighborList(); // neighbor list update
    loop.runForces(); // evaluate forces based on current particle configuration
    loop.runEvaluateObservables(t); // evaluate observables
}
```
And here you of course can omit the kernel initialization if you choose to continue running an existing configuration.

**Comment by clonker** [comment]
With the newest version (since merge of PR #139) you should be able to reset a simulation by calling `stateModel.clear()`.
Best,
Moritz
