### ISSUE TITLE
Change ColorID in `convert_trajectory_to_xyz`

### ISSUE THREAD

**Issue by tomkau93** [readdy/readdy#159]
Right now the users can set the particle radii via `trajectory.convert_to_xyz(particle_radii = particle_radii)`. This will write the particle radii to the `.h5.xyz.tcl` file. 
In the same file are ColorID references which are used for example by VMD to display the particles. 

As the source code for `convert_trajectory_to_xyz` is not accesible on GitHub (it's in `readdy._internal`) I don't really understand in which order the particle types are added to the `.tcl` file and thus at what basis the different ColorIDs are assigned.

It would be great to be able to change the ColorID in the same way as the particle radii. However, I would also be thankful if you could clarify in which order the different particle types are added to the `.tcl` file
Thanks in advance!

**Comment by clonker** [comment]
Hi, you can see the source code that is used to convert to xyz [here](https://github.com/readdy/readdy/blob/1d332989d616d8b4316af9ab7e533606e9f4680b/wrappers/python/src/cxx/common/Utils.cpp#L172). Currently the ColorID is written incrementally into the `tcl` file and until we have implemented setting it from the python side of things the best thing you can do is manually change the tcl. The order of the types is arbitrary at this point, so this is something that needs to be implemented.

**Comment by tomkau93** [comment]
Hi there, thanks for the fast response!

I guess then for now I will change the ColorID manually in the `.h5.xyz.tcl` file.

**Comment by tomkau93** [comment]
I came up with a hacky way to change the color in case anyone else has the same problem. 

`species` is the list of species in the order they were added to the system and `colors` is a dictionary with the different species as keys and integers as values

```python
with open('test.h5.xyz.tcl') as f:
    tcl_lines = f.readlines()

for i in range(len(species)):
    current_type = (tcl_lines[4+4*i+1].split('type_')[1]).split('\n')[0]
    tcl_lines[4+4*i+2] = re.sub('[0-9]+', colors[current_type], tcl_lines[4+4*i+2])

with open('test.h5.xyz.tcl', 'w') as f:
    f.writelines(tcl_lines)

```

**Comment by clonker** [comment]
As of #160 (ie with the newest dev version) you can pass a dictionary with `{"species_name": colorid} to the `convert_to_xyz` command, overriding the consecutively assigned color ids.
