### ISSUE TITLE
Disabling show_progress leads to segmentation fault

### ISSUE THREAD

**Issue by tomkau93** [readdy/readdy#161]
Some of my simulations broke at runtime and returned a *Segmentation fault* error. I realized that it only happened for simulations which included the line `simulation.show_progress = False`.
I updated to the newest release via conda (v2.0.1) but the error remained. 
Once I deleted the line, the simulations ran without a problem.

This small example below recreates the error:
```python 
import readdy

system = readdy.ReactionDiffusionSystem([25.,25.,25.], temperature=300.*readdy.units.kelvin)
simulation = system.simulation(kernel="CPU")
simulation.output_file = "out.h5"

simulation.show_progress = False
simulation.run(n_steps=10000, timestep=1e-2)
```

The output I get is:
```
--------------------------------
 - kBT = 2.49434
 - periodic b.c. = (true, true, true)
 - box size = (25, 25, 25)
 - particle types:

Segmentation fault (core dumped)
```

**Comment by clonker** [comment]
Huh that is curious. Can you try and run it on the latest dev version? That means running
```
conda update -c readdy/label/dev readdy
```
The version `import readdy; readdy.__version__` should then report `v2.0.2-7`. If that didn't do the trick, what is your installed tqdm version?

**Comment by clonker** [comment]
I could just reproduce it, fix is incoming with the next dev release (ie after merging the PR with the fix).

**Comment by tomkau93** [comment]
Cool, thanks for the fix :)

**Comment by clonker** [comment]
This should be resolved now, please feel free to reopen if you still experience that issue.
