### ISSUE TITLE
make_checkpoints function

### ISSUE THREAD

**Issue by JoulesJ** [readdy/readdy#168]
Hi,

from the online documentation I understand, that the function should work as follows:

simulation.make_checkpoints(1000, output_directory="checkpoints/", max_n_saves=10)
simulation.make_checkpoints(stride=1000, output_directory="checkpoints/", max_n_saves=10)

However, I get the error, that "output_directory" is an unexpected keyword and if I leave it out (by writing simulation.make_checkpoints(1000)), the simulation runs but no checkpoints are saved. 

Is there anything obvious that I am doing wrong?

Thanks in advance,
Julia

**Comment by clonker** [comment]
Hi, I suspect that you are running on the latest release and not on the development branch. Please try to run `conda install -c readdy/label/dev readdy -f` and see if it works then. The checkpointing was reworked a little but I dont think there has been a minor release yet - my bad!

**Comment by JoulesJ** [comment]
Hi, thank you very much for your reply. I did as you suggested. Now the checkpointing is working. However, now there is some issue with adding a structural reaction (TypeError: add_structural_reaction() missing 1 required positional argument: 'rate_function'). Before it worked as follows:
system.topologies.add_structural_reaction("filament", dissociation, rate), where dissociation is the required function.

**Comment by chrisfroe** [comment]
Hi Joules, there was another slight change in the usage of `add_structural_reaction`, as now you have to give the reaction itself a name (as with normal reactions). In your case this means you should do
```python
system.topologies.add_structural_reaction("mydissociation", "filament", dissociation, rate)
```
where `mydissociation` is a name you choose.

This change has not yet found its way into documentation, sorry for that!

(This change was necessary to enable counting of reaction events for topology reactions)

**Comment by JoulesJ** [comment]
Ah ok, great! Thank you for that information.
