### ISSUE TITLE
Each topology is limited to one reaction per time step

### ISSUE THREAD

**Issue by ilyasku** [readdy/readdy#175]
It appears that one topology can only be involved in one reaction each time step. Is that by design or is it a bug? I am interested in simulation of polymer networks, which can form a single giant topology, but limitation of one reaction per topology would be an issue.

In case you want to reproduce this, I can give you the code. But it should also be easy to rebuild a similar scenario. I created two short polymers, which are almost touching at their central beads. I allowed four reactions:
1. `attach`: A free monomer binds to the head of one polymer.
2. `link`: A bond forms between the two polymers, merging it into one topology. The bound beads change their type to motor.
3. `filament-dissolve`: The tail of the polymer detaches and becomes a free monomer.
4. `motor-step`: the motor bead passes its state to the next core bead, and changes its own type to core in turn.

I cranked up the rates s.th. almost every step all reactions should happen (the highest rate is on `link`, so the two topologies merge in the first step). I monitored the reaction_counts, and it shows only one reaction happening at a time:

```
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 1}, {'filament-dissolve': 0, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 1, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 1, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 1, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 0, 'motor-step': 1})
obs.reaction_counts callback: ({}, {'attach': 0, 'link': 0}, {'filament-dissolve': 1, 'motor-step': 0})
```

**Comment by clonker** [comment]
Yes exactly, this is by design and of course an approximation of what might actually be happening. 
In a little more detail, it is one topology reaction per topology per call of the topology reaction handler. So right now i can see two relatively easy to implement solutions:
The simple but simulation time consuming solution is a smaller timestep, but instead you could also call the topology reaction evaluation handler multiple times per timestep (configured with a respectively smaller timestep to not speed up reactions artificially).

**Comment by clonker** [comment]
If you are comfortable with it you can try and get it to work on your own, the relevant code is in `include/readdy/api/SimulationLoop.h`. In particular the loop itself is located around likes 277-295. Otherwise I can also give you some more pointers / draft up an implementation. :)

**Comment by ilyasku** [comment]
Allright, thanks for the quick response. I am not completely sure of the impact of reaction limit on my simulation. I will try to get a better picture of that before I meddle in the code.
So, since this is by design, I will close the issue. But I also really like the idea of an option to configure the reaction handlers to run n times per each simulation time step... let's see if I find the time. Maybe I will return again in a few weeks with a pull request. ;)
