### ISSUE TITLE
Diffusion Patterns Repeating

### ISSUE THREAD

**Issue by ilyasku** [readdy/readdy#180]
I encountered some issue in long simulations of linear polymers. I wanted to validate that my polymers show expected diffusion of polymers. For that I revert the minimum image projection similar to the way in your MSD validation example. I look at the trajectories of a beads that are rather central in the polymer for my analysis. But the trajectories show a repeating pattern: 

![reverted_traj](https://user-images.githubusercontent.com/1101201/79584489-c67e3680-80ce-11ea-9ee9-ff5e9678b8fa.png)

I was certain I must have done something stupid in the minimum image reversion, or in interactions between the particles and the polymer topolgy or something like that. But the pattern shows also with the minimum image projection (in some examples where the long-term direction is along one of the cardinal axes, this is nicely visible; sorry the plots are not that nice, color coded is the time, dark blue at the beginning of the simulation, light yellow at the end):

![traj_frames_4300_10350](https://user-images.githubusercontent.com/1101201/79585399-085bac80-80d0-11ea-926a-67e27f0ffca4.png)

I tried to reproduce this with rather simple code as well, e.g. with:

```
import numpy as np
import readdy
import os

stride = int(1e5)
n_steps = int(1e8)
progress_output_stride = int(1e5)
dt = 1e-3


system = readdy.ReactionDiffusionSystem(box_size=[60., 60., 60.],
                                        unit_system=None)

system.topologies.add_type("Polymer")
system.add_topology_species("Head", 1.)
system.add_topology_species("Core", 1.)

system.topologies.configure_harmonic_bond("Head", "Core", force_constant=70, length=1.)
system.topologies.configure_harmonic_bond("Core", "Core", force_constant=70, length=1.)
system.topologies.configure_harmonic_angle("Core", "Core", "Core", force_constant=5., equilibrium_angle=np.pi)
system.topologies.configure_harmonic_angle("Core", "Core", "Head", force_constant=5., equilibrium_angle=np.pi)
system.topologies.configure_harmonic_angle("Head", "Core", "Head", force_constant=5., equilibrium_angle=np.pi)


simulation = system.simulation(kernel="SingleCPU")

init_top_pos = np.zeros((10, 3))
init_top_pos[:, 0] = np.arange(-5, 5)
top = simulation.add_topology("Polymer", ["Head"] + ["Core"]*8 + ["Head"], init_top_pos)
for i in range(9):
    top.get_graph().add_edge(i, i+1)

simulation.output_file = "data.h5"
simulation.observe.particle_positions(stride=stride)
simulation.record_trajectory(stride=stride)
simulation.progress_output_stride = progress_output_stride

if os.path.exists(simulation.output_file):
    os.remove(simulation.output_file)

simulation.run(n_steps=n_steps, timestep=dt)
```

This code leads to similar patterns. And even for diffusion of single particles without any interactions (I had 9 particles in a box simulated for 1e10 time steps, recorded every 1e4 steps, D=1, dt=1e-3, box=[50, 50, 50]), here shown for the first 60000 recorded frames of one of the particles:

![traj_single_particles_higher_framerate](https://user-images.githubusercontent.com/1101201/79586752-d8ada400-80d1-11ea-94df-3efededfc548.png)

For other particles in the box, the same pattern shows, but they start at a different point of the cycle:

![traj_single_particles_higher_framerate_particle_0](https://user-images.githubusercontent.com/1101201/79586820-ecf1a100-80d1-11ea-8652-6873fe8d1c14.png)

I am not sure what to make of this. Did I miss something obvious? Do I have to do something like choose a proper random number generator for rather long simulations? Or is this an expected behaviour in simulations of free diffusion for many time steps due to limitations of pseudo random number generators? Can you reproduce this or is this an artifact specific to my set up (I already tried it on 3 devices, but the set up might be very similar on all)?

**Comment by chrisfroe** [comment]
Yeah this shouldn't happen, the mersenne twister engine has a period of 2^19937-1. So something is amiss. Will look into this next week.

**Comment by chrisfroe** [comment]
Which version was this?

**Comment by chrisfroe** [comment]
Could reproduce this. The `std::default_random_engine` defaults (to my surprise) to a linear congruential engine with a rather small period. Fix incoming.

**Comment by ilyasku** [comment]
Perfect, thank you! This means I did not go mad :) And fortunately it was something easy to find.
That is really surprising indeed ... I will keep that in mind for following projects as well.

**Comment by clonker** [comment]
Huh, I wasn't aware of that default either. Good find!

**Comment by chrisfroe** [comment]
Yes thanks ilyasku, good catch.
