### ISSUE TITLE
Spatial Topology Reactions with Rate Function

### ISSUE THREAD

**Issue by ilyasku** [readdy/readdy#191]
It is currently not possible to define a rate function for spatial topology reactions. I would like to use a function there, to account for an (implicit) background concentration of some protein. Would it be possible to implement it such that a function as well as a float can be used as the rate argument in `system.topologies.add_spatial_reaction` ?

**Comment by clonker** [comment]
Hi, not without changing the c++ code. BUT I think that would be fairly easy. In the end all you would have to do is modify `SpatialTopologyReaction` so that the (currently scalar and constant) `_rate` field is a function call on evaluation (or perhaps have an evaluation mode and switch between constant rate and dynamic rate). This of course would have some performance implications. Anything else would work implicitly and demands no changes. Except for the Python interface if you want that.
Would you be willing to work on such functionality? I am happy to assist if you get stuck and/or want input.

**Comment by ilyasku** [comment]
Hi clonker, thanks for pointing me in the right direction. I can try to implement it. 
Switching between constant and dynamic rate would probably be better, such that performance is not impacted if one wants to use constant rate?
I will also need the Python interface, since I currently configure everything via Python. Would be nice to change at one point to C++ for better performance of the custom reaction functions, but I want to stick to Python for now.

**Comment by clonker** [comment]
> Switching between constant and dynamic rate would probably be better, such that performance is not impacted if one wants to use constant rate?
Yes exactly. Although as a first draft I think it is fine to just use functions everywhere. More important is the question what the arguments of the reaction rate function should be. In principle it could be a TT or a TP reaction (topology = T, particle =P), in which case I am guessing you would want two different rate function calls, assuming you would want the Topology and/or Particle as arguments. So this can make it a bit tricky. How is it in your application? Is it a position dependence?

Depending on how much time you want / can spend on this, you can also just 'hack' the desired functionality into the package on a fork and later we think about how to integrate it (if desired).
In any case, the Python interface is no big deal once the cpp side of things works. :-)

**Comment by ilyasku** [comment]
> More important is the question what the arguments of the reaction rate function should be. In principle it could be a TT or a TP reaction (topology = T, particle =P), in which case I am guessing you would want two different rate function calls, assuming you would want the Topology and/or Particle as arguments. So this can make it a bit tricky. How is it in your application? Is it a position dependence?

In my application it's only TT reactions, and it's position dependent. But in structural reactions my rate/reaction functions are usually methods of a class, and this class tracks e.g. the global number of a certain type of particles. Ideally I would do the same for the rate of the spatial reactions, then I could multiply a constant rate with the fraction of free particles (where free particles is an initial number of particles minus the number of reactions that already happened, or something like this, of which the class keeps track).

**Comment by clonker** [comment]
In that case I suggest to  add a new member `_rateFunction` of type `std::function<scalar(const GraphTopology&, const std::variant<GraphTopology, Particle>&)>` as well as a member `bool _isConstantRate`. The signature of `scalar rate() const` needs to be changed accordingly to accept TT and TP. Then, `SCPUEvaluateTopologyReactions` and `CPUEvaluateTopologyReactions` needs to be updated to accomodate these changes and finally the python bindings be implemented.

**Comment by ilyasku** [comment]
For TT reactions, this has been implemented with #192 . TP reactions could be implemented analogously, but the TT reactions are all I needed for now.

**Comment by clonker** [comment]
Thanks again for your contribution! Highly appreciated :-)
