### ISSUE TITLE
Manual compile and install lead to CPU kernel missing 

### ISSUE THREAD

**Issue by ilyasku** [readdy/readdy#193]
As I am currently meddling in the code, I want to compile via cmake and install the C++ libraries and the python wrapper to a python virtualenv.
It works fine if I change the `CMAKE_INSTALL_PREFIX` to my virtualenv. `readdy` get's installed and I can import it in python. But I can only create a simulation with kernel `"SingleCPU"` not with `"CPU"`: `ValueError: The selected kernel was "CPU" but only "SingleCPU" are available.` The folder `readdy/readdy_plugins` includes the file `libreaddy_kernel_cpu.so` and gets copied to my virtualenv, but it seems like it does not get found. I've seen in the code that plugins can be read from a plugin directory specified via environment variable `READDY_PLUGIN_DIR`, but that did not work. 
On a probably related note, if I want to run the unit tests via the executables in the `bin` dir, I can only do that directly from within the build dir, where there is the folder `readdy/readdy_plugins`, otherwise I get the error 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  file [readdy/readdy_plugins] did not exist or was a file.
```

What am I missing, where would I have to place the plugins folder to get found by readdy? A few months back I always used `conda-build`, and installed the produced conda package in a new environment. That always worked, but the folder layout looks identical, with the `readdy/readdy_plugins` folder inside the conda environment folder, and building with `conda-build` all the time is less convenient.

**Comment by clonker** [comment]
Hi, readdy expects the plugins to sit within `${CONDA_ENV_PATH}/readdy/readdy_plugins`. To directly install them there and later on use, you can use the following set of cmake configuration flags:

```
-DCMAKE_PREFIX_PATH=/home/${USER}/miniconda3/envs/readdydev
-DPYTHON_PREFIX=/home/${USER}/miniconda3/envs/readdydev/bin
-DREADDY_DEBUG_PYTHON_MODULES:BOOL=ON
-DREADDY_DEBUG_CONDA_ROOT_DIR=/home/${USER}/miniconda3/envs/readdydev
```

Otherwise you can also set the environment variable `CONDA_ENV_PATH` to the root of your conda environment given the plugins are under `readdy/readdy_plugins`.

**Comment by ilyasku** [comment]
Allright, thanks. I prefer to work with virtualenvironments rahter than conda. But with conda I get it running without any issues, so I'll use conda for now.

**Comment by clonker** [comment]
I understand. Never used virtualenv, so can't really comment on that. If you at some point want to go back to virtualenv and there are some cmake changes / lookup changes required to successfully load the kernels I am happy to help with that.
