### ISSUE TITLE
Problem with particles unique ids and vertexes indexes

### ISSUE THREAD

**Issue by miglesias92** [readdy/readdy#196]
Hello there,

I've been working with ReaDDy for a while, but a few weeks ago I reinstalled ReaDDy (I think a newer version than the one I had been using) and I have found several errors in codes that previously ran well. Some of these I was able to solve but I have found others that I cannot solve. In the simulations that I carry out, I use several molecules of the same topology. These molecules are made of 30 linearly connected particles. Previously when looping through these molecules with the following code:

for e in edges:
		v1_ref, v2_ref = e[0], e[1]
		v1 = v1_ref.get()
		v2 = v2_ref.get()
		a = [topology.particle_type_of_vertex(v1), topology.particle_type_of_vertex(v2)]
		b = [v1.particle_index, v2.particle_index]

variable b got indexes ranging from 0 to 29 for each of the strands. Now, using the same code, b gets indexes from 0 to 29 for the first molecule but from 29 to 59 for the second one and so on. That would not lead to any problems if it weren’t for the fact that when I want to perform a structural reactions, e.g. removing an edge between the provided vertexes, if the vertexes have indexes ranging from 29 to 59, the program crashes and tells me that the index, for example 40 is greater than “nVertices” which would be equal to 30 for each molecule. So briefly, I think the program is assigning the unique id of the particle instead of the index of the vertex. So, I think my problem will solved if I could have a command to call for the vertex index. 

Hope its clear!

Thanks! 

Best

Matias

**Comment by clonker** [comment]
Hi Matias,

sorry that you were having troubles with your update! We indeed updated the internal handling of topologies and while doing that removed (as you correctly suspected) an indirection: The particle indices in vertices are now particle indices belonging to the actual unique particles, not the ones within a topology instance. However, if you want to remove/add edges, you shouldn't need to provide indices. Could you try with `recipe.remove_edge(v1, v2)`? Or is your setup such that you definitely require indices?

Cheers, Moritz

**Comment by miglesias92** [comment]
Thank you very much for your help. I was able to fix my input code using v1 and v2 in the structural reaction as you suggested. 
best,
Matias

**Comment by clonker** [comment]
I am happy to hear that, please let us know if you have any more issues!
