### ISSUE TITLE
Simulation run problems

### ISSUE THREAD

**Issue by kaa-git** [readdy/readdy#197]
Hi!
I have faced with a non trivial problem to me while trying to run simulation with different initial conditions.
I was trying to simulate simple bimolecular reaction A+B->C in two cases:
1. Equal initial concentrations of A and B species
D_A = 1, D_B = 1, D_C = 1
L_x, L_y, L_z = 300, 300, 300
R_f = 500
N_A_0 = 50000, N_B_0 = 50000
T = 300
R_AB = 1
2. Species B in excess as compared to A species
D_A = 1, D_B = 1, D_C = 1
L_x, L_y, L_z = 1300, 1300, 1300
R_f = 500
N_A_0 = 50000, N_B_0 = 5000000
T = 300
R_AB = 1
In both cases other parameters were identical:
simulation = system.simulation(kernel="CPU")
simulation.output_file = "A+B-C.h5"
simulation.reaction_handler = "Gillespie"

initial_coords_A = L_x*np.random.random((N_A_0, 3)) - L_x/2
initial_coords_B = L_x*np.random.random((N_B_0, 3)) - L_x/2

simulation.add_particles(type = "A", positions = initial_coords_A)
simulation.add_particles(type = "B", positions = initial_coords_B)

simulation.observe.number_of_particles(stride=1, types = ["A"])

simulation.run(n_steps=8600, timestep=1e-2)
But final step (simulation.run(n_steps=8600, timestep=1e-2)) was failed in the second case (in the excess of B particles). Timestep=1e-2 was the same in the first case and simulation showed nice results.

**Comment by clonker** [comment]
Hey there! I have the suspicion that these are too many particles for your work machine to handle. Can you try to reduce number of B particles and A particles?
If that doesn't help, can you post the whole script and what kind of error youre getting?

Thanks!

**Comment by kaa-git** [comment]
I have reduced number of A and B particles to values 5000 and 500000, accordingly but the error still arises: "MemoryError: std::bad_alloc"
When number of A and B particles where reduced to 500 and 50000 there were not problems and simulation run. But we are interested in kinetics of A particles and its asympotic behaviour, and in that case there are too large concentration fluctuations observed. So the more A particles in simulation the better chance for us to investigate the kinetics in detail.
The whole script
`import readdy
print(readdy.__version__)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Setup ReaDDy system
D_A = 1
D_B = 1
D_C = 1

L_x, L_y, L_z = 690, 690, 690
N_A_0 = 5000
N_B_0 = 500000

R_f = 500
T = 300
R_AB = 1

kappa = np.sqrt(R_f / (D_A + D_B))
k_f = 4. * np.pi * (D_A + D_B) * R_AB * (1. - np.tanh(kappa * R_AB) / (kappa * R_AB) )

A_0 = N_A_0/(L_x*L_y*L_z)
B_0 = N_B_0/(L_x*L_y*L_z)

t_decay = -np.log(0.005)/(k_f*B_0)

system = readdy.ReactionDiffusionSystem([L_x, L_y, L_z],
                                       temperature=T*readdy.units.kelvin)
system.add_species("A", diffusion_constant = D_A)
system.add_species("B", diffusion_constant = D_B)
system.add_species("C", diffusion_constant = D_C)
system.reactions.add("association: A +(1) B -> C", rate = R_f)

# Simulate the system

simulation = system.simulation(kernel="CPU")
simulation.output_file = "out_A+B-C.h5"

simulation.reaction_handler = "Gillespie"

initial_coords_A = L_x*np.random.random((N_A_0, 3)) - L_x/2
initial_coords_B = L_x*np.random.random((N_B_0, 3)) - L_x/2

simulation.add_particles(type = "A", positions = initial_coords_A)
simulation.add_particles(type = "B", positions = initial_coords_B)

simulation.observe.number_of_particles(stride=1, types = ["A"])

if os.path.exists(simulation.output_file):
    os.remove(simulation.output_file)

delta_t = 1e-2
simulation.run(n_steps=int(t_decay/delta_t), timestep=delta_t)

traj = readdy.Trajectory(simulation.output_file)
time, counts = traj.read_observable_number_of_particles()


Thanks!

**Comment by clonker** [comment]
Hi there, I looked into it and it seems the simulation box is too large for the cutoff radius you are considering (cell linked lists take some space). If you reduce the dimensions of it it should work out fine!
`bad_memory ` basically means that you are running out of RAM.

**Comment by kaa-git** [comment]
Hi! It seems that the problem is really in the box size. But I have 50 Gb RAM in the machine and supposed it was sufficient. I have to control the concentration small enough with large number of particles. So the box size was calculated. I guess some parameters exceeds their permissible values when box size goes too large

**Comment by chrisfroe** [comment]
I'm closing this. Feel free to re-open, if your issue here is not resolved.
