### ISSUE TITLE
Problems while trying to get the index of a vertex neighbor 

### ISSUE THREAD

**Issue by miglesias92** [readdy/readdy#200]
Hello there,

I've found an error while trying to get the index of the neighbors of a particular vertex. Here is an example of the code I wrote to perform this action:

for v in vertices:
     a = vertices[v].neighbors()[0]
     b = vertices.index(a)

The error says:
ValueError: Vertex[particleIndex= n, data=, neighbors=[n, n]] is not in list

but if I print "vertices" I see that this vertex ("a") is indeed in the list.

Is it possible to check the index of a particular vertex's neighbor in "vertices"?   

Hope it's clear!

Thanks!

Best

Matias

**Comment by clonker** [comment]
Hi Matias,

this is likely because we don't have any equality operator implemented for vertices. Let me add that quickly and then let's see if it fixes your problem!

Cheers,
Moritz

**Comment by clonker** [comment]
The new development version should be online (`conda update readdy -c readdy/label/dev`), could you check again?

**Comment by miglesias92** [comment]
Thank you very much for your quick reply and help! I've just checked and the problem is fixed  
best,
Matias

**Comment by clonker** [comment]
Cool, closing this issue then. :slightly_smiling_face:
