### ISSUE TITLE
Fission rate constant

### ISSUE THREAD

**Issue by kaa-git** [readdy/readdy#231]
Hi there, I'm trying to validate reversible reaction like A+A=C. In order to apply the theory we should calculate the rates of fussion and fission reactions. The rate for fussion reaction in Doi model is known from literature. The question is about fission model. When we add the dissociation reaction we should provide the so-called "product_distance". It defines, as described in help, ("Their distance on this axis is at most product_distance") where particles to be born. Does it means that particles are fromed randomly, and their relative distance varyes from zero to "product_distance" uniformuly? That means that the probability to find particles after dissociation is proportional to Heaviside function theta(product_distance - r), where r - relative distance between particles? Or particles are created precisely with relative distance equal to "product_distance"? That would mean that the probability is proportional to Dirac function delta(product_distance - r)? Which of the two answers is correct? Or maybe non of them?) Thank you

**Comment by clonker** [comment]
Hi, because writing tex in github is a pain, i'll just copy a screenshot from the readdy paper here...

![image](https://github.com/readdy/readdy/assets/1685266/abb899a8-9bc9-4f74-95c4-83659fe0fb1f)

does this help?

**Comment by kaa-git** [comment]
Thank you for the useful answer. But I found some contradiction. From that one can conclude that, for example, if n is parallel to x1, then max(x1) = x0 + 0.5*Ru, and min(x2) = x0-0.5*Ru, and hence maximum distance between particles is Ru, so they are placed within a sphere of radius Ru/2, and not Ru, as mentioned

**Comment by clonker** [comment]
You are right, the wording is wrong here. The way it should be worded is in terms of a "product distance" d with x_0 = x - .5d and x_1 = x + .5d. Add random orientation and weights into the mix, then you got the implementation:

https://github.com/readdy/readdy/blob/master/include/readdy/kernel/singlecpu/actions/SCPUReactionUtils.h#L103

**Comment by kaa-git** [comment]
Ok. Thank you!
