### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by fhoefling** [readdy/readdy#3]
I couldn't find any licensing information for this project, and not all source files contain copyright messages.

Note that I'm about to re-license the h5xx library under the modified BSD terms and HALMD under LGPL-3.0.

**Comment by franknoe** [comment]
thanks, that's great!

Am 03/06/16 um 18:13 schrieb Felix Höfling:
>
> I couldn't find any licensing information for this project, and not 
> all source files contain copyright messages.
>
> Note that I'm about to re-license the h5xx library under the modified 
> BSD terms and HALMD under LGPL-3.0.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/readdy/readdy/issues/3>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AGMeQrTKTteox9TRucWyLG01j52ZLmMGks5qIFK1gaJpZM4ItrxL>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by clonker** [comment]
Thanks!
Yes, we still have to add the license headers and information for lgpl.

**Comment by clonker** [comment]
added LGPLv3 licensing information
