### ISSUE TITLE
Plugin structure for optional features

### ISSUE THREAD

**Issue by chrisfroe** [readdy/readdy#48]
_Note_: This will become relevant once we have a feature-complete core and a stable API.

It occurred to us already several times, that some features might not be necessary for every use-case, for example:
- calculation of energies, consumes cpu-time but might not be needed for a lot of applications
- reaction event reporting
- compartments (see #47 or [proposals](https://readdy.github.io/readdy_documentation/docpages/development/#development/proposals))

The problem with those is that they induce some data/fields that have to be present in the StateModel or the Context, thus they have to be declared in the core library and optimally be implemented in all the kernels (scpu, cpu, cuda, mpi). Some approaches one might take:
- introduce a __plugin structure__ that handles additional features in a similar fashion how kernels solve the different platforms
  - an advantage would be that the core library stays sleek in terms of functionality and dependecies, since additional features can be migrated to subprojects.
  - another advantage is performance. A certain set of those feature-plugins exactly matches a simulation-task, e.g. if you don't need to calculate the forces/energies, why bother carrying around the architecture for it in the memory?
  - a disadvantage is maintenance because one would introduce another dimension of programming-complexity. I.e. all those feature-subprojects have to be maintained. If something changes in the core library this must be reflected in all kernels and all feature-subprojects.
- agree on __necessary__ features, all of them will be in the core library. Everything else must be done via python prototyping or by writing another kernel with the missing features.
  - this means performance/memory overhead when a feature is in-place but not used. E.g. reaction-reporting could currently only be done by the reaction-handler. To be available to observables, the reporting will have a corresponding field in the StateModel.
  - maintenance is less complex
- map all these problems to __Actions__ that have their own data
  - this probably has lots of implications that I currently don't see ...

**Comment by clonker** [comment]
I think we solved this via the plugin structure.
