### ISSUE TITLE
Python2 support

### ISSUE THREAD

**Issue by chrisfroe** [readdy/readdy#74]
Canceling python2 support might have a few __advantages__
- Less overhead writing 2/3 compatible python modules
  - string-handling w.r.t. encoding
  - dictionary iterating
  - `from __future__` imports
- Obviously fewer travis jobs

Also
- readdy does not depend on py2-only packages
- there has not been a release of readdy

i.e. now it's still possible to cut support. We might have larger issues later.

**Comment by clonker** [comment]
Disabled python 2 in the build chain.
